# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-09 03:24
from __future__ import unicode_literals

import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 30 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=30, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+-]+$', 'Enter a valid username. This value may contain only letters, numbers and @/./+/-/_ characters.')], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('nickname', models.CharField(max_length=20, verbose_name='\u6635\u79f0')),
                ('avatar', models.ImageField(blank=True, default='avatar/default.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u7528\u6237\u5934\u50cf')),
                ('qq', models.CharField(blank=True, max_length=20, null=True, verbose_name='QQ\u53f7\u7801')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, unique=True, verbose_name='\u624b\u673a\u53f7\u7801')),
                ('url', models.URLField(blank=True, max_length=100, null=True, verbose_name='\u4e2a\u4eba\u7f51\u9875\u5730\u5740')),
                ('sex', models.CharField(choices=[('M', 'Man'), ('W', 'Woman'), ('D', 'Demon')], max_length=1, verbose_name='\u6027\u522b')),
                ('member', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': '\u7528\u6237',
                'verbose_name_plural': '\u7528\u6237',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=30, verbose_name='\u5206\u7c7b\u540d\u79f0')),
                ('category_num', models.IntegerField(default=100, verbose_name='\u663e\u793a\u8bfe\u7a0b\u7f16\u53f7(\u4ece\u5c0f\u5230\u5927)')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u5206\u7c7b\u540d\u79f0',
                'verbose_name_plural': '\u5206\u7c7b\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='class_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cls_name', models.CharField(max_length=30, verbose_name='\u8bfe\u7a0b\u540d\u79f0')),
                ('cls_num', models.IntegerField(default=100, verbose_name='\u663e\u793a\u8bfe\u7a0b\u7f16\u53f7(\u4ece\u5c0f\u5230\u5927)')),
                ('cls_date', models.DateTimeField(auto_now_add=True, verbose_name='\u8bfe\u7a0b\u4e0a\u67b6\u65f6\u95f4')),
                ('cls_desc', models.CharField(max_length=300, verbose_name='\u8bfe\u7a0b\u63cf\u8ff0')),
                ('category_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Category', verbose_name='\u5206\u7c7b\u540d\u79f0')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u8bfe\u7a0b\u540d\u79f0',
                'verbose_name_plural': '\u8bfe\u7a0b\u540d\u79f0',
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='\u8001\u5e08\u59d3\u540d')),
                ('introduction', models.CharField(max_length=300, verbose_name='\u81ea\u6211\u4ecb\u7ecd')),
            ],
            options={
                'ordering': ['id'],
                'verbose_name': '\u8001\u5e08\u59d3\u540d',
                'verbose_name_plural': '\u8001\u5e08\u59d3\u540d',
            },
        ),
        migrations.AddField(
            model_name='class_info',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='web.Teacher', verbose_name='\u8001\u5e08\u59d3\u540d'),
        ),
    ]
