# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-05-11 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170511_0715'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tea_img_url',
            field=models.ImageField(blank=True, default='course/12.png', max_length=200, null=True, upload_to='avatar/%Y/%m', verbose_name='\u8001\u5e08\u5934\u50cf'),
        ),
    ]
